package support

import java.time.LocalDate
import java.time.format.DateTimeFormatter
import java.time.format.TextStyle
import java.util.Locale

/**
 *  Test data Layer
 *  Centralised Souce for data models (User,Address)
 */

// Fixed constants useful across tests
object TestConstants {
    const val BASE_URL = "https://www.bet99.com/"
    const val DEFAULT_LANGUAGE = "English"
}

// data holder for sign up data for step 1
// data class autogenerated useful methods (equals, to string)
data class User(
    val username: String,
    val email: String,
    val firstName: String,
    val lastName: String,
    val dob: LocalDate,
    val promoCode: String? = null,
    val phone: String = "416${(1000000..9999999).random()}",
    val language: String = "English"
)

// data holder address lookup validation for step 2
data class Address(
    val lookup: String,          // free text typed in the “Address lookup” field
    val line1: String,           // expected populated value
    val city: String,
    val postalCode: String,
    val province: String,
    val country: String
)


// Acts like a small factory that generates reusable randomized but realistic data and uses uniqe values for each run
// Keeps randomization centralized so Page Objects/Steps stay clean.
object TestDataFactory {

    // Builds a valid user for positive paths:
    // - Unique username/email using a timestamp suffix
    // - Realistic age (25–40), with fixed month/day so dropdown selection is deterministic
    fun user(): User {
        val stamp = System.currentTimeMillis().toString().takeLast(6)
        return User(
            username = "qa$stamp",
            email = "qa$stamp@example.com",
            firstName = "Ash",
            lastName = "Gavai",
            dob = LocalDate.now().minusYears((25..40).random().toLong()).withMonth(5).withDayOfMonth(12)
        )
    }



    // Provides a known-good Toronto address that can be searched
    // and auto-populated in Step 2.
    fun addressToronto(): Address =
        Address(
            lookup = "1 Yonge Street, Toronto",
            line1 = "1 Yonge St",
            city = "Toronto",
            postalCode = "M5E 1W7",
            province = "Ontario",
            country = "Canada"
        )

    fun addressSaintRaphael(): Address =
        Address(
            lookup = "226 sa",
            line1 = "226 Saint-Raphael W St",
            city = "Sainte-Marie-Saint-Raphaël",
            postalCode = "E8T 1V3",
            province = "New Brunswick",
            country = "Canada"
        )


    // --- DOB formatting helpers for dropdowns on Step 1 ---
    // These convert LocalDate -> convert LocalDate parts into dropdown text values
    fun dobYmd(d: LocalDate) = d.format(DateTimeFormatter.ofPattern("yyyy"))
    fun dobMonth(d: LocalDate) = d.month.name.lowercase().replaceFirstChar { it.titlecase() } // "May"
    fun dobMonthShort(d: LocalDate) = d.month.getDisplayName(TextStyle.SHORT, Locale.ENGLISH)      // "Jan"
    fun dobDay(d: LocalDate) = "%02d".format(d.dayOfMonth)           // "01"
}
